default_language_version:
  python: python3.8

repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: ^docs/.*$
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: trailing-whitespace
        exclude: README.md
-   repo: git://github.com/asottile/pyupgrade
    rev: v2.24.0
    hooks:
    -   id: pyupgrade
-   repo: git://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: git://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
